apiVersion: v1
kind: Service
metadata:
   name: customer-app-svc
   labels:
     app: customer-app
spec:
   type: NodePort
   selector:
     app: customer-app
   ports:
     - port: 8080
       targetPort: 8080
       nodePort: 31000
